// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"dependncy-injection/business"
	"dependncy-injection/database"
	"dependncy-injection/service"
)

// Injectors from wire.go:

func InitializeService() service.Service {
	databaseDatabase := database.NewDatabase()
	businessBusiness := business.NewBusiness(databaseDatabase)
	serviceImpl := service.NewService(businessBusiness)
	return serviceImpl
}
